update deploy-gcp

diff --git a/.github/workflows/deploy-gcp.yaml b/.github/workflows/deploy-gcp.yaml
--- a/.github/workflows/deploy-gcp.yaml
+++ b/.github/workflows/deploy-gcp.yaml
@@ -47,20 +47,19 @@ jobs:
             - name: Pull files from GCS to web root via IAP tunnel
               run: |
                   COMMAND_OUTPUT=$(gcloud compute ssh ubuntu@${{ secrets.GCP_INSTANCE_NAME }} \
-                    --zone=us-central1-a \
-                    --project=${{ secrets.GCP_PROJECT_ID }} \
-                    --tunnel-through-iap \
-                    --command="
-                      gcloud storage rsync gs://andrewflanigan-site-deploy/site-deploy/ /var/www/andrewflanigan.com/ --recursive --delete-unmatched-destination-objects 2>&1
-                      echo 'Exit code: '$?
-                    " 2>&1)
+                      --zone=us-central1-a \
+                      --project=${{ secrets.GCP_PROJECT_ID }} \
+                      --tunnel-through-iap \
+                      --command="
+                      sudo gcloud storage rsync gs://andrewflanigan-site-deploy/site-deploy/ /var/www/andrewflanigan.com/ --recursive --delete-unmatched-destination-objects 2>&1
+                      echo 'Exit code: '\$?
+                      " 2>&1)
 
                   echo "$COMMAND_OUTPUT"
 
-                  # Fail the workflow if the remote command failed
                   if echo "$COMMAND_OUTPUT" | grep -q "Exit code: [^0]"; then
-                    echo "Remote sync failed"
-                    exit 1
+                      echo "Remote sync failed"
+                      exit 1
                   fi
 
             - name: Clean up GCS staging bucket
