Update workflow (#28)
* Update workflow

* update workflow

diff --git a/.github/workflows/deploy-gcp.yaml b/.github/workflows/deploy-gcp.yaml
--- a/.github/workflows/deploy-gcp.yaml
+++ b/.github/workflows/deploy-gcp.yaml
@@ -4,6 +4,7 @@ on:
     push:
         branches:
             - main
+    workflow_dispatch:
 
 permissions:
     id-token: write
@@ -50,10 +51,11 @@ jobs:
                       --zone=us-central1-a \
                       --project=${{ secrets.GCP_PROJECT_ID }} \
                       --tunnel-through-iap \
-                      --command="
-                      sudo gcloud storage rsync gs://andrewflanigan-site-deploy/site-deploy/ /var/www/andrewflanigan.com/ --recursive --delete-unmatched-destination-objects 2>&1
-                      echo 'Exit code: '\$?
-                      " 2>&1) || true
+                      --command="whoami 2>&1; echo 'Exit code: '\$?"
+                    #   --command="
+                    #   sudo gcloud storage rsync gs://andrewflanigan-site-deploy/site-deploy/ /var/www/andrewflanigan.com/ --recursive --delete-unmatched-destination-objects 2>&1
+                    #   echo 'Exit code: '\$?
+                    #   " 2>&1) || true
 
                   echo "$COMMAND_OUTPUT"
 
